- platform: template
  sensors:
    anyone_home:
      device_class: presence
      friendly_name: "Anyone Home"
      value_template: >-
        {{ states('sensor.device_presence_confidence') | float > 10 }}
    hot_tub_cold:
      value_template: >-
        {{ sensor.hot_tub < 100 }}

- platform: trend
  sensors:
    hot_tub_falling:
      entity_id: sensor.hot_tub
      sample_duration: 7200
      min_gradient: -0.0008
      device_class: cold


#- platform: bayesian
#  name: Anyone Home
#  prior: 0.4
#  probability_threshold: 0.8
#  observations:
#    - entity_id: device_tracker.chibierkriss_iphone
#      prob_given_true: 0.9
#      prob_given_false: 0.5
#      platform: 'state'
#      to_state: 'Home'
#    - entity_id: input_boolean.sleep_mode
#      prob_given_true: 1.0
#      prob_given_false: 0.05
#      platform: 'state'
#      to_state: 'on'
#    - entity_id: device_tracker.ometepe
#      prob_given_true: 0.9
#      prob_given_false: 0.5
#      platform: 'state'
#      to_state: 'Home'
#    - entity_id: binary_sensor.motion_sensor_158d0001f9b8a1
#      prob_given_true: 0.95
#      prob_given_false: 0.5
#      platform: 'state'
#      to_state: 'on'
#    - entity_id: binary_sensor.duplex_away
#      prob_given_true: 0.9
#      prob_given_false: 0.1
#      platform: 'state'
#      to_state: 'off'
#    - entity_id: proximity.home
#      prob_given_true: 0.95
#      platform: 'numeric_state'
#      below: 1
