#- platform: broadlink
#  host: 192.168.86.195
#  mac: '34:ea:34:bb:12:2b'
#  friendly_name: Air Conditioner
#  type: rm_mini
#  switches:
#    livingroom_ac:
#      friendly_name: "Air Conditioner"
#      command_on: 'JgBYAAABJZQVEBQRFBETNxQRExEUERQRFDYVEBQ2FRAUNhU1FTUVNRU1FRAVEBUQFTUVEBUQFBEUEBU1FTYUNhUQFDYVNRU1FQAFUAABKEcVAAxpAAEmRxQADQU=='
#      command_off: 'JgBYAAABJZQVEBQRFBETNxQRExEUERQRFDYVEBQ2FRAUNhU1FTUVNRU1FRAVEBUQFTUVEBUQFBEUEBU1FTYUNhUQFDYVNRU1FQAFUAABKEcVAAxpAAEmRxQADQU=='


- platform: broadlink
  #  host: 192.168.86.21
  host: 192.168.86.195
  mac: '78:0f:77:00:79:02'
  friendly_name: Bedroom AC
  type: rm_mini
  switches:
    bedroom_ac:
      friendly_name: "Bedroom AC"
      command_on: JgDKAJGREzUSEhI2EjYTERISEjYSEhISEjYTERISEjYSNhMREjYSNxISEjYSNhI2EjUSNhI2EhMSNRITExESEhMREhISEhMREhISNhISEhITEhISEhISNhI2EhISNhI2EjUTNRQ0Eq2RkRM1EhISNhI2EhISEhI2EhISEhI2EhISEhI2EjYTERI2EjYUEBI2EjYSNhI2EjYSNhISEjYUEBISEhISEhISEhMSEhISEjYSEhISEhISEhISEjYSNhISEjYSNhI2EjYSNhIADQUAAAAAAAAAAAAAAAAAAA==
      command_off: JgDKAJKREzUSEhM1EzUTERMREjYTERMREzUSEhISEzUTNRMREzUTEhI1EzUTNRM1ExETNRM1EzUTERMSEhISEhM1EhITERM1EjYTNRMRExETERMRExESExIRExISNhI2EjUTNRM1Eq2SkBMzFRETNRM1ExETERM1EhITERM1ExETERM1EzUTERM1ExISNhI1EzUTNRMSEjUTNRM2EhISEhISExETMxURExESNhM1EzUTERMRExETERMRExISEhISEzUSNhI2EjUTNRIADQUAAAAAAAAAAAAAAAAAAA==
###      command_off: JgDKAJOOEzUSEhM0EzUTERMREzUTERMREzUTERMREzUTNBMREzUTEhISEhISNRM1ETcSNRM1EzUTNRM1EhIRExETERMRExETEjYRExETETYRExETERMRNxETETcRNxETETcRNhE3E6yQkRE2ERMRNxE3ERMRExE3ERMRExE3ERMRExE3ETYRExE3ERMRExETETcRNxE3ETYRNxE3ETcRNxETERMRExETERMRExE3EhIRExI1EhISEhISEjYSEhI2EjYTERI2EjUSNhQADQUAAAAAAAAAAAAAAAAAAA==
###        command_74: JgDKAJCRETcRExE2ETcRExETETcRExETETcRExETETYRNxETETcRExETERMRNxE3ETYRNxE3ETcRNhE3ERMRExETERMRExETETcRExE3ETcRExESEhMRNhETETcRExETETcRNxE2E6yRkBE2ERMRNxE3ERMRExE2EhMRExE2ERMRExE3ETcRExE3ERMRExETETYSNhE3ETcRNhE3EzURNxETERMRExETERMRExE3ERMRNhI2ERMRExETETcRExE3ERMRExE2EjYRNxMADQUAAAAAAAAAAAAAAAAAAA==
###        command_72: JgDKAJCRETcRExE3ETYRExETETcRExETETcRExETETcRNhISETcRExETERMRNxE3EjYSNRM1EjYTNRM1ExETERMRExETERMREzQUNBQ0EzUTERMRExETNRMRExETERMREzQUNBM1FKmTjhQ0FBATNRM1ExETERM1ExETERM1ExETERM0FDQTERM1ExETERMREzUTNBQ0EzUTNRM1EzQUNBMRExETERISExETERI2EjYSNhI1ExETERMSEjUSEhISEhISEhI2EjYSNRQADQUAAAAAAAAAAAAAAAAAAA==
    bedroom_fan:
      friendly_name: "Bedroom Fan"
      command_on: JgDKAJGRFDQTERI2FDQUEBISFDQUEBQREjYTERQQEjYTNRMREzUSNhQQEhIUNBQ0FDQUNBQ0ExEUNBI2ExEUEBQQFBASEhI2FDQUNBQQFBAUNBQQFBAUERISEhISNhI2ExETNRI2EqyRkBQ0EhMTNRE2FBETERM0ExITERQ0FBASEhQ0EjYUEBI2EjYSEhQQFDQUNBM1EjYUNBQQFDQSNhISFBASEhISEhISNhI2FDQSEhISFDQUEBQRExESEhISEjYSNhMRFDQSNhIADQUAAAAAAAAAAAAAAAAAAA==
      command_off: JgDKAJGREjYUEBI2EjYSEhMREjYSEhITETcSEhISEjYTNRISEjYSEhI2EjYSNhI2EhISNhI2EzUSEhMREhITERI2EhISEhI3EjUTNRITEhISEhISEhITERISEhISNhI2EzUTNRM1Eq2RkRQ0EhITNRI2EhISEhI2EhITERI2EhISExI1EjYTEhI2EhISNhI2EjYSNRITEjYSNhI2ExESEhISExESNhISEhISNhI2FDQSEhMSEhISEhISEhITERMREjYTNRI2EzUSNhIADQUAAAAAAAAAAAAAAAAAAA== 

#- platform: tplink
#  host: 192.168.86.245
#- platform: tplink
#  host: 192.168.86.31

#- platform: flux
#  lights:
#    - light.couch_light
#    - light.makeup_light_1
#    - light.makeup_light_2
#  start_colortemp: 4500
#  sunset_colortemp: 3500
#  stop_colortemp: 2700
#  stop_time: '22:00'
#  mode: mired
#  interval: 10

#- platform: command_line
#  switches:
#    playstation4:
#      command_on: 'npx ps4-waker -d 192.168.86.29 -c /home/pi/.ps4-wake.credentials.json'
#      command_off: 'npx ps4-waker standby -d 192.168.86.29 -c /home/pi/.ps4-wake.credentials.json'
#      command_state: 'nc -z -w 5 192.168.86.29 9295'
#      friendly_name: "PS4"
#
- platform: mqtt
  name: "bedroom power 1"
  state_topic: "stat/bedroom_power/RESULT"
  value_template: "{{ value_json.POWER1 }}"
  command_topic: "cmnd/bedroom_power/POWER1"
  availability_topic: "tele/bedroom_power/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
- platform: mqtt
  name: "bedroom power 2"
  state_topic: "stat/bedroom_power/RESULT"
  value_template: "{{ value_json.POWER2 }}"
  command_topic: "cmnd/bedroom_power/POWER2"
  availability_topic: "tele/bedroom_power/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
- platform: mqtt
  name: "bedroom power 3"
  state_topic: "stat/bedroom_power/RESULT"
  value_template: "{{ value_json.POWER3 }}"
  command_topic: "cmnd/bedroom_power/POWER3"
  availability_topic: "tele/bedroom_power/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
- platform: mqtt
  name: "bedroom power 4"
  state_topic: "stat/bedroom_power/RESULT"
  value_template: "{{ value_json.POWER4 }}"
  command_topic: "cmnd/bedroom_power/POWER4"
  availability_topic: "tele/bedroom_power/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false

- platform: command_line
  switches:
    pihole_switch:
      command_on: "curl -X GET 'http://192.168.86.20/admin/api.php?enable&auth=8ee69b0712d255f83bd51f5cc50fb21ac975327f2252a084a219509e62209a6f'"
      command_off: "curl -X GET 'http://192.168.86.20/admin/api.php?disable=60&auth=8ee69b0712d255f83bd51f5cc50fb21ac975327f2252a084a219509e62209a6f'"
      command_state: "curl -X GET 'http://192.168.86.20/admin/api.php?status&auth=8ee69b0712d255f83bd51f5cc50fb21ac975327f2252a084a219509e62209a6f'"
      value_template: "{{ value_json.status == 'enabled' }}"
